// Fallback Coffee Shop Data
// Generated automatically when API is offline

const List<Map<String, dynamic>> fallbackCoffeeShops = [
  {
    'id': 'fb_1',
    'name' : 'Time Coffee',
    'address' : 'Jl. Ketintang Sel. No.63',
    'latitude' : -7.3170094,
    'longitude' : 112.7232219,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'Time Coffee hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : true, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_2',
    'name' : 'POS Cafe',
    'address' : 'Jl. Ketintang Sel. No.1',
    'latitude' : -7.3178984,
    'longitude' : 112.7257525,
    'price' : 13000,
    'rating' : 4.5,
    'description' : 'Tempat nongkrong favorit di Jl. Ketintang Sel. No.1. POS Cafe menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_3',
    'name' : 'Pená Coffee & Roastery',
    'address' : 'Jl. Gayung Kebonsari No.133 kav. 1',
    'latitude' : -7.3286129,
    'longitude' : 112.7252972,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Kedai kopi modern dengan cita rasa klasik. Pená Coffee & Roastery siap menemani hari-harimu.',
    'facilities' : {'wifi' : true, 'outdoor' : true, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_4',
    'name' : 'Vervins Coffee',
    'address' : 'Jl. Ketintang Sel. No.93',
    'latitude' : -7.31589,
    'longitude' : 112.720697,
    'price' : 25000,
    'rating' : 4.5,
    'description' : 'Tempat nongkrong favorit di Jl. Ketintang Sel. No.93. Vervins Coffee menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : true, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_5',
    'name' : 'EKNOR COFFEE & EATERY',
    'address' : 'Blok MGN, Taman, Jl. Gayungsari Tim. No.09',
    'latitude' : -7.338503,
    'longitude' : 112.7227448,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'EKNOR COFFEE & EATERY - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_6',
    'name' : 'Uban Coffee',
    'address' : 'Jl. Jemur Andayani XIX No.4',
    'latitude' : -7.3287005,
    'longitude' : 112.7367844,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Uban Coffee hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_7',
    'name' : 'Brain Coffee Surabaya',
    'address' : 'Jl. Wonokromo Tangkis No.52',
    'latitude' : -7.3029544,
    'longitude' : 112.7319984,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'Brain Coffee Surabaya - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_8',
    'name' : 'Tanah Kopi - Margorejo',
    'address' : 'Jl. Margorejo No.60e',
    'latitude' : -7.3146994,
    'longitude' : 112.7389522,
    'price' : 13000,
    'rating' : 4.7,
    'description' : 'Kedai kopi modern dengan cita rasa klasik. Tanah Kopi - Margorejo siap menemani hari-harimu.',
    'facilities' : {'wifi' : true, 'outdoor' : true, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_9',
    'name' : 'Bagi Kopi Signature - Margorejo Indah',
    'address' : 'Jl. Margorejo Indah No.511',
    'latitude' : -7.317874,
    'longitude' : 112.7453327,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'Bagi Kopi Signature - Margorejo Indah menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_10',
    'name' : 'BARA CAFE',
    'address' : 'Brick-lined hub for familiar fast food',
    'latitude' : -7.335074,
    'longitude' : 112.7162828,
    'price' : 37500,
    'rating' : 4.7,
    'description' : 'BARA CAFE - Cafe dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : true, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_11',
    'name' : 'Kofind Coffee Co.',
    'address' : 'Jl. Kebonsari Tengah No.103',
    'latitude' : -7.3295793,
    'longitude' : 112.7118063,
    'price' : 37500,
    'rating' : 4.9,
    'description' : 'Kofind Coffee Co. hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : false, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_12',
    'name' : 'Titik Koma Ketintang Riverside',
    'address' : 'Jl. Ketintang Brt. No.13',
    'latitude' : -7.3086944,
    'longitude' : 112.7219387,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'Nikmati suasana ngopi terbaik di Titik Koma Ketintang Riverside. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_13',
    'name' : 'Oi Kafe',
    'address' : 'Jl. Ketintang Madya No.187',
    'latitude' : -7.3221999,
    'longitude' : 112.721579,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Oi Kafe menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_14',
    'name' : 'Lini Kopi. Id',
    'address' : 'Kantor Pos, Jl. Gayung Kebonsari No.42a',
    'latitude' : -7.3285187,
    'longitude' : 112.7198864,
    'price' : 37500,
    'rating' : 4.8,
    'description' : 'Lini Kopi. Id menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_15',
    'name' : 'The Little Prince Coffee',
    'address' : 'Jl. Musi No.20',
    'latitude' : -7.2860678,
    'longitude' : 112.7345952,
    'price' : 37500,
    'rating' : 4.8,
    'description' : 'Nikmati suasana ngopi terbaik di The Little Prince Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : false}
  },
  {
    'id': 'fb_16',
    'name' : 'Ultra Coffee',
    'address' : 'Jl. Cipunegara No.46, RT.016/RW.06',
    'latitude' : -7.291607,
    'longitude' : 112.7296129,
    'price' : 62500,
    'rating' : 4.7,
    'description' : 'Nikmati suasana ngopi terbaik di Ultra Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_17',
    'name' : 'Arung Senja',
    'address' : 'Blok AD No, Ketintang Selatan IX No.1',
    'latitude' : -7.3206991,
    'longitude' : 112.7216225,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Arung Senja hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_18',
    'name' : 'The Vinyl Chick Cafe',
    'address' : 'Jl. Gayungsari I No.79',
    'latitude' : -7.3336309,
    'longitude' : 112.720898,
    'price' : 37500,
    'rating' : 4.8,
    'description' : 'Tempat nongkrong favorit di Jl. Gayungsari I No.79. The Vinyl Chick Cafe menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_19',
    'name' : 'D\'VOTEE COFFEE',
    'address' : 'Jl. Margorejo No.mor 129',
    'latitude' : -7.3147614,
    'longitude' : 112.7395887,
    'price' : 37500,
    'rating' : 4.8,
    'description' : 'Tempat nongkrong favorit di Jl. Margorejo No.mor 129. D\'VOTEE COFFEE menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_20',
    'name' : 'Toko kopi Padma - Jemursari',
    'address' : 'Jl. Raya Jemursari No.167',
    'latitude' : -7.31893,
    'longitude' : 112.748648,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Toko kopi Padma - Jemursari - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_21',
    'name' : 'KEDAIKOE COFFE',
    'address' : 'Jl. Ketintang Sel. No.55',
    'latitude' : -7.3171528,
    'longitude' : 112.7236406,
    'price' : 25000,
    'rating' : 4.3,
    'description' : 'Tempat nongkrong favorit di Jl. Ketintang Sel. No.55. KEDAIKOE COFFE menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_22',
    'name' : 'Djogelo Coffe',
    'address' : 'Jl. Ketintang Baru I No.20',
    'latitude' : -7.3185109,
    'longitude' : 112.730506,
    'price' : 25000,
    'rating' : 4.6,
    'description' : 'Djogelo Coffe menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_23',
    'name' : 'Kedai Te Co Java, homey coffee shop',
    'address' : 'Jl. Kutisari III No.7',
    'latitude' : -7.3300634,
    'longitude' : 112.7472064,
    'price' : 13000,
    'rating' : 5,
    'description' : 'Kedai Te Co Java, homey coffee shop hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_24',
    'name' : 'De Java Coffee Beans',
    'address' : 'Jl. Puri Jambangan Baru III No.4',
    'latitude' : -7.3202124,
    'longitude' : 112.7200821,
    'price' : 25000,
    'rating' : 5,
    'description' : 'Tempat nongkrong favorit di Jl. Puri Jambangan Baru III No.4. De Java Coffee Beans menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_25',
    'name' : 'kopi M legacy',
    'address' : 'MPJC+9QQ',
    'latitude' : -7.3190276,
    'longitude' : 112.7219997,
    'price' : 25000,
    'rating' : 5,
    'description' : 'kopi M legacy menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_26',
    'name' : '118th Coffee',
    'address' : 'Jl. Siwalankerto No.118',
    'latitude' : -7.339762,
    'longitude' : 112.734969,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Nikmati suasana ngopi terbaik di 118th Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_27',
    'name' : 'Völks Coffee | Specialty Coffee',
    'address' : 'Jl. Jambi No.21, RT.003/RW.05',
    'latitude' : -7.2927885,
    'longitude' : 112.7342035,
    'price' : 50000,
    'rating' : 4.5,
    'description' : 'Völks Coffee | Specialty Coffee menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : false}
  },
  {
    'id': 'fb_28',
    'name' : 'Yoiki kopi & Waffles',
    'address' : 'Jl. Ketintang No.42',
    'latitude' : -7.3084237,
    'longitude' : 112.7261384,
    'price' : 13000,
    'rating' : 4.8,
    'description' : 'Tempat nongkrong favorit di Jl. Ketintang No.42. Yoiki kopi & Waffles menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_29',
    'name' : 'A Coffee',
    'address' : 'Jl. Ketintang Wiyata IV No.30, RT.002/RW.004',
    'latitude' : -7.3127209,
    'longitude' : 112.7240649,
    'price' : 25000,
    'rating' : 5,
    'description' : 'Tempat nongkrong favorit di Jl. Ketintang Wiyata IV No.30, RT.002/RW.004. A Coffee menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_30',
    'name' : 'Baradjawa Coffee - Gayungsari',
    'address' : 'Taman Jl. Gayungsari Bar. II No.12',
    'latitude' : -7.3314452,
    'longitude' : 112.7181276,
    'price' : 37500,
    'rating' : 4.7,
    'description' : 'Baradjawa Coffee - Gayungsari hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_31',
    'name' : 'Dee Coffee House',
    'address' : 'Perumahan Graha Tirta, Jl. Tirta Raya No.21',
    'latitude' : -7.3532598,
    'longitude' : 112.7383682,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'Kedai kopi modern dengan cita rasa klasik. Dee Coffee House siap menemani hari-harimu.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_32',
    'name' : 'Fifteenth Cafe by Mark Design',
    'address' : 'Jl. Lombok No.15',
    'latitude' : -7.2781271,
    'longitude' : 112.7466016,
    'price' : 37500,
    'rating' : 4.9,
    'description' : 'Fifteenth Cafe by Mark Design hadir dengan konsep cafe yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_33',
    'name' : 'Loca Coffee Polda Jatim',
    'address' : 'Jl. Ahmad Yani No.116',
    'latitude' : -7.323809,
    'longitude' : 112.7302261,
    'price' : 25000,
    'rating' : 4.8,
    'description' : 'Loca Coffee Polda Jatim hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_34',
    'name' : 'The Rocketman Coffee Gayungan',
    'address' : 'Jl. Ketintang Baru Sel. I No.3 Blok A3',
    'latitude' : -7.3243466,
    'longitude' : 112.726741,
    'price' : 13000,
    'rating' : 4.6,
    'description' : 'The Rocketman Coffee Gayungan hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_35',
    'name' : 'OPEKAFE',
    'address' : 'Jl. Ketintang 1 No.4b',
    'latitude' : -7.3069195,
    'longitude' : 112.726962,
    'price' : 13000,
    'rating' : 4.9,
    'description' : 'OPEKAFE menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_36',
    'name' : 'Team Gorylla Surabaya',
    'address' : 'Surabaya',
    'latitude' : -7.3083238,
    'longitude' : 112.7327559,
    'price' : 25000,
    'rating' : 4.9,
    'description' : 'Team Gorylla Surabaya - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_37',
    'name' : 'Warkop Bang Faris',
    'address' : 'Jl. Frontage Timur, Jl. Ahmad Yani No.161',
    'latitude' : -7.3302805,
    'longitude' : 112.7314029,
    'price' : 13000,
    'rating' : 4.7,
    'description' : 'Warkop Bang Faris hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_38',
    'name' : 'Gekkopi',
    'address' : 'Jl. Pulo Wonokromo Blok PL-13 No.259, RT.006/RW.02',
    'latitude' : -7.3040135,
    'longitude' : 112.7273674,
    'price' : 25000,
    'rating' : 4.9,
    'description' : 'Gekkopi menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_39',
    'name' : 'TIEWUS COFFEE BREAK 02',
    'address' : 'Jl. Ketintang Baru II A No.11, RT.001/RW.07',
    'latitude' : -7.3109346,
    'longitude' : 112.73246,
    'price' : 25000,
    'rating' : 4.5,
    'description' : 'Kedai kopi modern dengan cita rasa klasik. TIEWUS COFFEE BREAK 02 siap menemani hari-harimu.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : false}
  },
  {
    'id': 'fb_40',
    'name' : 'Cold \'N Brew - Jemursari',
    'address' : 'Jl. Raya Jemursari No.82',
    'latitude' : -7.3227996,
    'longitude' : 112.7433542,
    'price' : 37500,
    'rating' : 4.5,
    'description' : 'Nikmati suasana ngopi terbaik di Cold \'N Brew - Jemursari. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_41',
    'name' : 'BC SGI Warkop Podomampir',
    'address' : 'MPGC+GM3, Jl. Gayung Kebonsari Timur',
    'latitude' : -7.3237317,
    'longitude' : 112.7216664,
    'price' : 25000,
    'rating' : 4.4,
    'description' : 'Nikmati suasana ngopi terbaik di BC SGI Warkop Podomampir. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_42',
    'name' : 'Roshe Coffee',
    'address' : 'Jl. Jagir Wonokromo No.39',
    'latitude' : -7.3004108,
    'longitude' : 112.7382266,
    'price' : 13000,
    'rating' : 4.4,
    'description' : 'Nikmati suasana ngopi terbaik di Roshe Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_43',
    'name' : 'Starbucks',
    'address' : 'Iconic coffeehouse chain',
    'latitude' : -7.3200831,
    'longitude' : 112.73233,
    'price' : 62500,
    'rating' : 4.6,
    'description' : 'Starbucks - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_44',
    'name' : 'Demandailing Cafe',
    'address' : 'Jl. Raya Jemursari No.71',
    'latitude' : -7.3225321,
    'longitude' : 112.7423232,
    'price' : 62500,
    'rating' : 4.5,
    'description' : 'Demandailing Cafe hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_45',
    'name' : 'Kedai Pulang Kantor',
    'address' : 'Jl. Jemur Andayani No.17 A',
    'latitude' : -7.3278152,
    'longitude' : 112.7374768,
    'price' : 13000,
    'rating' : 4.7,
    'description' : 'Kedai Pulang Kantor menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_46',
    'name' : 'Bess Coffee',
    'address' : 'Jl. Raya Jemursari No.15A',
    'latitude' : -7.3267428,
    'longitude' : 112.7330526,
    'price' : 62500,
    'rating' : 4.6,
    'description' : 'Bess Coffee hadir dengan konsep coffee shop yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_47',
    'name' : 'Dhe Bams Cafe',
    'address' : 'Jl. Ketintang Tengah No.8',
    'latitude' : -7.3126617,
    'longitude' : 112.7283598,
    'price' : 25000,
    'rating' : 4.6,
    'description' : 'Dhe Bams Cafe menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_48',
    'name' : 'RUKOPI (Coffee Shop, Co - Work & Virtual Office)',
    'address' : 'Ruko Gateway, Jl. Raya Waru C-11',
    'latitude' : -7.3677712,
    'longitude' : 112.7280451,
    'price' : 37500,
    'rating' : 4.8,
    'description' : 'Nikmati suasana ngopi terbaik di RUKOPI (Coffee Shop, Co - Work & Virtual Office). Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_49',
    'name' : 'Crema Coffee - Jemursari VI',
    'address' : 'Jl. Jemursari VI No.2',
    'latitude' : -7.3215274,
    'longitude' : 112.7429612,
    'price' : 13000,
    'rating' : 4.7,
    'description' : 'Crema Coffee - Jemursari VI - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_50',
    'name' : 'Jengki Cafe',
    'address' : 'Jl. Gayungsari Tim. I No.14',
    'latitude' : -7.3375527,
    'longitude' : 112.7204565,
    'price' : 37500,
    'rating' : 4.7,
    'description' : 'Jengki Cafe hadir dengan konsep cafe yang unik dan menu kopi yang beragam.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_51',
    'name' : 'Excelso - SUB A Yani',
    'address' : 'Jl. Ahmad Yani No.72-74',
    'latitude' : -7.318691,
    'longitude' : 112.7327464,
    'price' : 75000,
    'rating' : 4.6,
    'description' : 'Tempat nongkrong favorit di Jl. Ahmad Yani No.72-74. Excelso - SUB A Yani menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : false}
  },
  {
    'id': 'fb_52',
    'name' : 'Koopi Co-Working Space',
    'address' : 'Jl. Raya Jemursari No.76 D09',
    'latitude' : -7.323368,
    'longitude' : 112.7423015,
    'price' : 25000,
    'rating' : 4.9,
    'description' : 'Kedai kopi modern dengan cita rasa klasik. Koopi Co-Working Space siap menemani hari-harimu.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : false, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_53',
    'name' : 'NYALA COFFEE by FIRST CRACK',
    'address' : 'Ciputra World Surabaya Lt. 2 Unit 80-82, Jl. Mayjen Sungkono No.89',
    'latitude' : -7.2930273,
    'longitude' : 112.7193437,
    'price' : 37500,
    'rating' : 4.7,
    'description' : 'NYALA COFFEE by FIRST CRACK - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_54',
    'name' : 'Point Coffee',
    'address' : 'Jl. Gayungsari Tim. IV No.14a',
    'latitude' : -7.3377323,
    'longitude' : 112.7214777,
    'price' : 37500,
    'rating' : 4.7,
    'description' : 'Nikmati suasana ngopi terbaik di Point Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_55',
    'name' : 'Cup of Hope Coffee',
    'address' : 'Jl. Opak No.20',
    'latitude' : -7.2890628,
    'longitude' : 112.7345523,
    'price' : 37500,
    'rating' : 4.9,
    'description' : 'Nikmati suasana ngopi terbaik di Cup of Hope Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_56',
    'name' : 'Point Coffee',
    'address' : 'Jl. Gn. Sari III No No.5-I, RT.003/RW.09',
    'latitude' : -7.3063779,
    'longitude' : 112.723756,
    'price' : 37500,
    'rating' : 4.6,
    'description' : 'Nikmati suasana ngopi terbaik di Point Coffee. Tempat yang nyaman untuk bersantai dan menikmati kopi pilihan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_57',
    'name' : 'Eco coffe',
    'address' : 'Jl. Raya Jetis Kulon I No.65',
    'latitude' : -7.3068976,
    'longitude' : 112.7300491,
    'price' : 13000,
    'rating' : 4.7,
    'description' : 'Eco coffe - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : false, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  },
  {
    'id': 'fb_58',
    'name' : 'Point Coffee - Ayani 68 Surabaya (TRTS)',
    'address' : 'Jl. Ahmad Yani No.68',
    'latitude' : -7.3181271,
    'longitude' : 112.7330794,
    'price' : 13000,
    'rating' : 4.8,
    'description' : 'Point Coffee - Ayani 68 Surabaya (TRTS) - Coffee shop dengan racikan kopi spesial dan interior yang instagramable.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : true}
  },
  {
    'id': 'fb_59',
    'name' : 'Mountain Coffee Shop',
    'address' : 'Jl. Ngagel No.127b',
    'latitude' : -7.2894596,
    'longitude' : 112.7441407,
    'price' : 37500,
    'rating' : 4.4,
    'description' : 'Tempat nongkrong favorit di Jl. Ngagel No.127b. Mountain Coffee Shop menawarkan kopi premium dan suasana yang menyenangkan.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : false, 'smoking_room' : true}
  },
  {
    'id': 'fb_60',
    'name' : 'Rustic Market Forest Tree',
    'address' : 'Jl. Golf 1 Surabaya No.159 A',
    'latitude' : -7.3052095,
    'longitude' : 112.7132605,
    'price' : 75000,
    'rating' : 4.5,
    'description' : 'Rustic Market Forest Tree menyajikan kopi berkualitas dengan suasana yang cozy. Cocok untuk kerja atau hangout.',
    'facilities' : {'wifi' : true, 'outdoor' : false, 'ac' : true, 'sockets' : true, 'smoking_room' : false}
  }
];
